# Creating numpy/n-d arrays


In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)

numpy.ndarray

In [6]:
arr2=np.array([[1,2,3,],[4,55,6]])

In [7]:
arr2

array([[ 1,  2,  3],
       [ 4, 55,  6]])

In [8]:
arr3=np.zeros((3,4))

In [9]:
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
arr4=np.ones((4,4))
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
arr5=np.identity(3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
aarr6=np.arange(5,16,2)
aarr6

array([ 5,  7,  9, 11, 13, 15])

In [21]:
arr7=np.linspace(10,25,13)
arr7

array([10.  , 11.25, 12.5 , 13.75, 15.  , 16.25, 17.5 , 18.75, 20.  ,
       21.25, 22.5 , 23.75, 25.  ])

In [22]:
arr8=arr7.copy()
arr8

array([10.  , 11.25, 12.5 , 13.75, 15.  , 16.25, 17.5 , 18.75, 20.  ,
       21.25, 22.5 , 23.75, 25.  ])

# Some Important Attributes

### Shape

In [29]:

arr2.shape

(2, 3)

In [32]:
arr9=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [33]:
arr9.shape

(2, 2, 2)

In [34]:
arr2.ndim

2

In [35]:
arr2.size

6

In [36]:
arr2.itemsize

8

In [37]:
arr9.itemsize

8

In [38]:
arr2.dtype

dtype('int64')

In [39]:
arr2.astype('float')

array([[ 1.,  2.,  3.],
       [ 4., 55.,  6.]])

In [40]:
arr2.itemsize

8

# List V/S Arrays

## Size

In [42]:
lista=range(100)
arr11=np.arange(100)

In [43]:
import sys

In [ ]:
print(sys.getsizeof(87)* len(lista))


2800


In [46]:
print(arr11.itemsize* arr11.size)

800


## Time

In [47]:
import time

In [48]:
x=range(100000)
y=range(100000,200000)

start_time=time.time()
c=[x+y for x,y in zip(x,y)]
print(time.time()-start_time)

0.011345386505126953


In [50]:
a=np.arange(100000)
b=np.arange(100000,200000)
start_time=time.time()
c=a+b
print(time.time()-start_time)

0.002707242965698242


# Indexing, Slicing and Iteration

In [51]:
arr12=np.arange(30)
arr12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [53]:
arr12.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [54]:
arr[3]

np.int64(4)

In [61]:
arr12[-3]

np.int64(27)

In [63]:
for i in arr12:
    print (i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


In [64]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


# Numpy Operations

In [67]:
arr13=np.array([1,2,3,4,5,6])
arr14=np.array([7,8,9,10,11,12])
arr14-arr13

array([6, 6, 6, 6, 6, 6])

In [68]:
arr14* arr13

array([ 7, 16, 27, 40, 55, 72])

In [69]:
arr14*3

array([21, 24, 27, 30, 33, 36])

In [70]:
arr14+2

array([ 9, 10, 11, 12, 13, 14])

In [71]:
arr14.max()

np.int64(12)

In [72]:
arr14.min()

np.int64(7)

In [73]:
arr14.sum()

np.int64(57)

In [74]:
arr14.std()

np.float64(1.707825127659933)

In [75]:
np.sin(arr14)

array([ 0.6569866 ,  0.98935825,  0.41211849, -0.54402111, -0.99999021,
       -0.53657292])

In [76]:
np.median(arr14)

np.float64(9.5)

In [ ]:
np.exp(arr14)

array([  1096.63315843,   2980.95798704,   8103.08392758,  22026.46579481,
        59874.1417152 , 162754.791419  ])

# Reshaping Numpy Arrays

In [78]:
arr14.ndim

1

In [82]:
arr14.reshape(2,3)

array([[ 7,  8,  9],
       [10, 11, 12]])

In [86]:
arr4.ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [88]:
arr12.transpose()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [89]:
arr12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [90]:
arr13

array([1, 2, 3, 4, 5, 6])